name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-drafter:
    name: Release Drafter
    environment: release-drafter
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@eada3c96a64734dd381cfbda23511034e328ddb0 # v7.6.0
        id: drafter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          toolchain: "1.95"

      - name: Install cargo-edit
        run: cargo install --locked cargo-edit

      - name: Bump Cargo.toml + Cargo.lock
        run: cargo set-version ${{ steps.drafter.outputs.resolved_version }}

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "Bump version to ${{ steps.drafter.outputs.resolved_version }}"
            git push
          fi
